"""Seed 50+ Indian government schemes

Revision ID: 002
Revises: 001
Create Date: 2026-07-03 22:30:00.000000

"""

# flake8: noqa

import json
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMES = [
    {
        "name": "Pradhan Mantri Kisan Samman Nidhi",
        "name_hindi": "प्रधानमंत्री किसान सम्मान निधि",
        "category": "agriculture",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "eligibility_criteria": {"land_ownership": "All landholding farmer families", "income_limit": "Not applicable", "exclusions": ["Income tax payers", "Government employees", "Constitutional office holders"]},
        "benefits": {"type": "Direct Benefit Transfer", "amount": "₹6,000 per year", "frequency": "Quarterly instalments of ₹2,000"},
        "required_documents": ["Aadhaar Card", "Land Records", "Bank Account", "Mobile Number"],
    },
    {
        "name": "Pradhan Mantri Fasal Bima Yojana",
        "name_hindi": "प्रधानमंत्री फसल बीमा योजना",
        "category": "agriculture",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "eligibility_criteria": {"farmer_type": "All farmers including sharecroppers and tenant farmers", "loan_status": "Both loanee and non-loanee farmers"},
        "benefits": {"type": "Crop Insurance", "coverage": "Up to 90% of sum insured", "premium": "2% for Kharif, 1.5% for Rabi, 5% for commercial/horticulture"},
        "required_documents": ["Aadhaar Card", "Land Records", "Crop Details", "Bank Account"],
    },
    {
        "name": "Pradhan Mantri Krishi Sinchayee Yojana",
        "name_hindi": "प्रधानमंत्री कृषि सिंचाई योजना",
        "category": "agriculture",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "eligibility_criteria": {"target": "All farmers in water-stressed areas", "land_ownership": "Must have cultivable land"},
        "benefits": {"type": "Irrigation Infrastructure", "coverage": "Micro-irrigation, drip irrigation, sprinkler systems", "subsidy": "Up to 55% for small and marginal farmers"},
        "required_documents": ["Aadhaar Card", "Land Records", "Bank Account", "Passport Photo"],
    },
    {
        "name": "Pradhan Mantri Awas Yojana - Gramin",
        "name_hindi": "प्रधानमंत्री आवास योजना - ग्रामीण",
        "category": "housing",
        "ministry": "Ministry of Rural Development",
        "eligibility_criteria": {"household_type": "Households with no pucca house", "income_limit": "Below poverty line households", "exclusions": ["Households with motorized vehicles", "Income tax payers"]},
        "benefits": {"type": "Housing Assistance", "amount": "₹1.20 lakh in plains, ₹1.30 lakh in hilly areas", "additional": "₹12,000 for toilet construction under Swachh Bharat"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Land Document", "Bank Account"],
    },
    {
        "name": "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana",
        "name_hindi": "आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना",
        "category": "health",
        "ministry": "Ministry of Health and Family Welfare",
        "eligibility_criteria": {"target": "Bottom 40% of population", "bedridden": "Based on SECC database"},
        "benefits": {"type": "Health Insurance", "coverage": "₹5 lakh per family per year", "treatment": "Cashless treatment at empanelled hospitals", "diseases": "Coverage for 1,949 procedures across 26 specialties"},
        "required_documents": ["Aadhaar Card", "SECC Database Verification", "Mobile Number"],
    },
    {
        "name": "Pradhan Mantri Mudra Yojana",
        "name_hindi": "प्रधानमंत्री मुद्रा योजना",
        "category": "finance",
        "ministry": "Ministry of Finance",
        "eligibility_criteria": {"business_type": "Non-corporate, non-farm small business", "income_limit": "No income limit", "age": "18 years and above"},
        "benefits": {"type": "Loan", "coverage": "Up to ₹10 lakh", "categories": "Shishu (up to ₹50k), Kishor (₹50k-₹5L), Tarun (₹5L-₹10L)"},
        "required_documents": ["Aadhaar Card", "Business Plan", "Identity Proof", "Address Proof"],
    },
    {
        "name": "Pradhan Mantri Jan Dhan Yojana",
        "name_hindi": "प्रधानमंत्री जन धन योजना",
        "category": "finance",
        "ministry": "Ministry of Finance",
        "eligibility_criteria": {"citizenship": "Indian citizen", "existing_account": "No existing bank account required", "age": "10 years and above"},
        "benefits": {"type": "Bank Account", "coverage": "Zero balance account", "features": "Rupay debit card, ₹1 lakh accident cover, ₹30,000 life cover", "overdraft": "Up to ₹5,000 after 6 months of satisfactory operation"},
        "required_documents": ["Aadhaar Card", "Mobile Number", "Passport Size Photo"],
    },
    {
        "name": "Sukanya Samriddhi Yojana",
        "name_hindi": "सुकन्या समृद्धि योजना",
        "category": "finance",
        "ministry": "Ministry of Finance",
        "eligibility_criteria": {"child_gender": "Girl child only", "child_age": "Below 10 years at time of account opening", "max_children": "Maximum 2 accounts per family (except twin girls in second birth)"},
        "benefits": {"type": "Savings Scheme", "interest_rate": "8.2% per annum (compounded yearly)", "tax_benefits": "EEE status under Income Tax Act", "maturity": "21 years from account opening or marriage after 18 years"},
        "required_documents": ["Girl Child's Birth Certificate", "Parent/Guardian Aadhaar", "Address Proof"],
    },
    {
        "name": "Atal Pension Yojana",
        "name_hindi": "अटल पेंशन योजना",
        "category": "pension",
        "ministry": "Ministry of Finance",
        "eligibility_criteria": {"age": "18 to 40 years", "bank_account": "Must have savings bank account", "income_tax_payer": "Not applicable"},
        "benefits": {"type": "Pension", "pension_amount": "₹1,000 to ₹5,000 per month", "government_contribution": "50% of contribution (up to ₹1,000 per year) for 5 years", "maturity": "60 years"},
        "required_documents": ["Aadhaar Card", "Bank Account", "Mobile Number"],
    },
    {
        "name": "Pradhan Mantri Garib Kalyan Anna Yojana",
        "name_hindi": "प्रधानमंत्री गरीब कल्याण अन्न योजना",
        "category": "food",
        "ministry": "Ministry of Consumer Affairs, Food and Public Distribution",
        "eligibility_criteria": {"target": "NFSA beneficiaries (Antyodaya and Priority Households)", "ration_card": "Must have valid ration card"},
        "benefits": {"type": "Free Food Grains", "quantity": "5 kg per person per month", "additional": "1 kg chana per family per month"},
        "required_documents": ["Ration Card", "Aadhaar Card", "Family Members List"],
    },
    {
        "name": "National Social Assistance Programme",
        "name_hindi": "राष्ट्रीय सामाजिक सहायता कार्यक्रम",
        "category": "social_welfare",
        "ministry": "Ministry of Rural Development",
        "eligibility_criteria": {"target": "BPL households", "age_pension": "60 years and above (IGNOAPS)", "widow_pension": "40-59 years (IGNVPS)", "disability_pension": "18-79 years (IGNDPS)"},
        "benefits": {"type": "Social Pension", "pension_amount": "₹200-₹500 per month depending on category"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Age Proof", "Bank Account"],
    },
    {
        "name": "Pradhan Mantri Matru Vandana Yojana",
        "name_hindi": "प्रधानमंत्री मातृ वंदना योजना",
        "category": "women_child",
        "ministry": "Ministry of Women and Child Development",
        "eligibility_criteria": {"target": "Pregnant and lactating women", "age": "19 years and above", "child_count": "First live birth"},
        "benefits": {"type": "Cash Transfer", "amount": "₹5,000 in three instalments", "conditions": "Registration, ANC checkup, vaccination, breastfeeding"},
        "required_documents": ["Aadhaar Card", "MCP Card", "Bank Account", "Marriage Certificate"],
    },
    {
        "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana",
        "name_hindi": "प्रधानमंत्री जीवन ज्योति बीमा योजना",
        "category": "insurance",
        "ministry": "Ministry of Finance",
        "eligibility_criteria": {"age": "18 to 50 years", "bank_account": "Must have savings bank account", "consent": "Auto-debit consent required"},
        "benefits": {"type": "Life Insurance", "sum_assured": "₹2 lakh", "premium": "₹436 per year", "coverage": "Death due to any reason"},
        "required_documents": ["Aadhaar Card", "Bank Account", "Mobile Number"],
    },
    {
        "name": "Pradhan Mantri Suraksha Bima Yojana",
        "name_hindi": "प्रधानमंत्री सुरक्षा बीमा योजना",
        "category": "insurance",
        "ministry": "Ministry of Finance",
        "eligibility_criteria": {"age": "18 to 70 years", "bank_account": "Must have savings bank account"},
        "benefits": {"type": "Accident Insurance", "sum_assured": "₹2 lakh (accidental death), ₹1 lakh (permanent disability)", "premium": "₹20 per year"},
        "required_documents": ["Aadhaar Card", "Bank Account", "Mobile Number"],
    },
    {
        "name": "Mahatma Gandhi National Rural Employment Guarantee Act",
        "name_hindi": "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम",
        "category": "employment",
        "ministry": "Ministry of Rural Development",
        "eligibility_criteria": {"residence": "Rural areas", "age": "18 years and above", "willingness": "Willing to do unskilled manual work"},
        "benefits": {"type": "Guaranteed Employment", "days": "100 days per household per year", "wage": "As per state minimum wage (varies by state)", "additional": "Work within 5 km radius, otherwise extra allowance"},
        "required_documents": ["Aadhaar Card", "Bank Account", "Job Card", "Voter ID"],
    },
    {
        "name": "Deendayal Antyodaya Yojana - National Rural Livelihoods Mission",
        "name_hindi": "दीनदयाल अंत्योदय योजना - राष्ट्रीय ग्रामीण आजीविका मिशन",
        "category": "livelihood",
        "ministry": "Ministry of Rural Development",
        "eligibility_criteria": {"target": "Rural BPL households", "group_formation": "Women Self Help Groups"},
        "benefits": {"type": "Livelihood Support", "support": "Community investment fund, skill training, bank linkages", "interest_subvention": "7% on bank loans up to ₹3 lakh"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Bank Account"],
    },
    {
        "name": "Pradhan Mantri Kaushal Vikas Yojana",
        "name_hindi": "प्रधानमंत्री कौशल विकास योजना",
        "category": "skill_development",
        "ministry": "Ministry of Skill Development and Entrepreneurship",
        "eligibility_criteria": {"age": "15 to 45 years", "education": "8th pass (varies by course)", "target": "School/college dropouts and unemployed youth"},
        "benefits": {"type": "Skill Training", "duration": "2-12 months depending on course", "certification": "Government recognized certificate", "stipend": "Monetary reward on certification"},
        "required_documents": ["Aadhaar Card", "Education Certificate", "Bank Account", "Photo"],
    },
    {
        "name": "Stand-Up India Scheme",
        "name_hindi": "स्टैंड-अप इंडिया योजना",
        "category": "finance",
        "ministry": "Ministry of Finance",
        "eligibility_criteria": {"target": "SC, ST and women entrepreneurs", "age": "18 years and above", "business": "Greenfield enterprise in manufacturing, services, or trading"},
        "benefits": {"type": "Loan", "amount": "₹10 lakh to ₹1 crore", "repayment": "Up to 7 years", "margin_money": "10% minimum"},
        "required_documents": ["Aadhaar Card", "Caste Certificate (SC/ST)", "Business Plan", "Bank Account"],
    },
    {
        "name": "Rani Laxmi Bai Mahila Samman Yojana",
        "name_hindi": "रानी लक्ष्मी बाई महिला सम्मान योजना",
        "category": "social_welfare",
        "eligibility_criteria": {"gender": "Women only", "marital_status": "All women", "residence": "Uttar Pradesh residents"},
        "benefits": {"type": "Cash Transfer", "amount": "₹5,000 per month"},
        "required_documents": ["Aadhaar Card", "Bank Account", "Address Proof"],
    },
    {
        "name": "National Scholarship Portal - Central Sector Scheme",
        "name_hindi": "राष्ट्रीय छात्रवृत्ति पोर्टल - केंद्रीय क्षेत्र योजना",
        "category": "education",
        "ministry": "Ministry of Education",
        "eligibility_criteria": {"education": "Top 1% students in Class 12 board exams", "income_limit": "Parental income up to ₹8 lakh per year", "course": "Pursuing graduate or postgraduate degree"},
        "benefits": {"type": "Scholarship", "amount": "₹10,000 for general, ₹20,000 for professional courses"},
        "required_documents": ["Aadhaar Card", "Marksheet", "Income Certificate", "Bank Account"],
    },
    {
        "name": "Pre-Matric Scholarship for SC Students",
        "name_hindi": "एससी छात्रों के लिए पूर्व-मैट्रिक छात्रवृत्ति",
        "category": "education",
        "ministry": "Ministry of Social Justice and Empowerment",
        "eligibility_criteria": {"caste": "SC category", "class": "9th and 10th standard", "income_limit": "Parental income up to ₹2.5 lakh per year"},
        "benefits": {"type": "Scholarship", "amount": "₹350 per month for day scholars, ₹525 for hostellers"},
        "required_documents": ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Bank Account"],
    },
    {
        "name": "Pre-Matric Scholarship for ST Students",
        "name_hindi": "एसटी छात्रों के लिए पूर्व-मैट्रिक छात्रवृत्ति",
        "category": "education",
        "ministry": "Ministry of Tribal Affairs",
        "eligibility_criteria": {"caste": "ST category", "class": "9th and 10th standard", "income_limit": "Parental income up to ₹2.5 lakh per year"},
        "benefits": {"type": "Scholarship", "amount": "₹400 per month for day scholars, ₹650 for hostellers"},
        "required_documents": ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Bank Account"],
    },
    {
        "name": "Post-Matric Scholarship for SC/ST Students",
        "name_hindi": "एससी/एसटी छात्रों के लिए उत्तर-मैट्रिक छात्रवृत्ति",
        "category": "education",
        "ministry": "Ministry of Social Justice and Empowerment",
        "eligibility_criteria": {"caste": "SC/ST category", "education": "Post-matric level (Class 11 onwards)", "income_limit": "Parental income up to ₹2.5 lakh per year"},
        "benefits": {"type": "Scholarship", "amount": "Full tuition fee reimbursement, maintenance allowance ₹230-₹1,200/month"},
        "required_documents": ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Bank Account"],
    },
    {
        "name": "Ujjwala Yojana",
        "name_hindi": "उज्ज्वला योजना",
        "category": "energy",
        "ministry": "Ministry of Petroleum and Natural Gas",
        "eligibility_criteria": {"target": "BPL households", "gender": "Women above 18 years", "exclusion": "Existing LPG connection holders"},
        "benefits": {"type": "LPG Connection", "subsidy": "Free LPG connection + first refill + stove"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Bank Account", "Photo"],
    },
    {
        "name": "Swachh Bharat Mission - Gramin",
        "name_hindi": "स्वच्छ भारत मिशन - ग्रामीण",
        "category": "sanitation",
        "ministry": "Ministry of Drinking Water and Sanitation",
        "eligibility_criteria": {"target": "Rural households without toilet facilities"},
        "benefits": {"type": "Toilet Construction", "amount": "₹12,000 per household", "additional": "Community sanitary complexes, solid liquid waste management"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Land Document"],
    },
    {
        "name": "Beti Bachao Beti Padhao",
        "name_hindi": "बेटी बचाओ बेटी पढ़ाओ",
        "category": "women_child",
        "ministry": "Ministry of Women and Child Development",
        "eligibility_criteria": {"target": "Districts with low child sex ratio", "beneficiary": "Girl children and their families"},
        "benefits": {"type": "Awareness and Support", "features": "Cash incentives for girl child education, awareness campaigns"},
        "required_documents": ["Aadhaar Card", "Birth Certificate"],
    },
    {
        "name": "Janani Suraksha Yojana",
        "name_hindi": "जननी सुरक्षा योजना",
        "category": "health",
        "ministry": "Ministry of Health and Family Welfare",
        "eligibility_criteria": {"target": "Pregnant women from BPL families", "age": "19 years and above"},
        "benefits": {"type": "Cash Transfer", "amount": "₹1,400 in rural areas, ₹1,000 in urban areas", "condition": "Institutional delivery"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Mother and Child Protection Card"],
    },
    {
        "name": "Rashtriya Swasthya Bima Yojana",
        "name_hindi": "राष्ट्रीय स्वास्थ्य बीमा योजना",
        "category": "health",
        "ministry": "Ministry of Health and Family Welfare",
        "eligibility_criteria": {"target": "BPL families, building workers, street vendors, beedi workers", "family_size": "Up to 5 members"},
        "benefits": {"type": "Health Insurance", "coverage": "₹30,000 per family per year", "premium": "₹30 registration fee per year"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Bank Account"],
    },
    {
        "name": "Pradhan Mantri Shram Yogi Maan-dhan",
        "name_hindi": "प्रधानमंत्री श्रम योगी मान-धन",
        "category": "pension",
        "ministry": "Ministry of Labour and Employment",
        "eligibility_criteria": {"age": "18 to 40 years", "income": "Monthly income up to ₹15,000", "occupation": "Unorganized sector workers"},
        "benefits": {"type": "Pension", "pension_amount": "₹3,000 per month after 60 years", "contribution": "₹55-₹200 per month based on age"},
        "required_documents": ["Aadhaar Card", "Bank Account", "Mobile Number"],
    },
    {
        "name": "National Food Security Act",
        "name_hindi": "राष्ट्रीय खाद्य सुरक्षा अधिनियम",
        "category": "food",
        "ministry": "Ministry of Consumer Affairs, Food and Public Distribution",
        "eligibility_criteria": {"target": "Up to 75% rural and 50% urban population", "ration_card": "Valid ration card required"},
        "benefits": {"type": "Subsidized Food Grains", "wheat": "₹2 per kg", "rice": "₹3 per kg", "coarse_grains": "₹1 per kg", "quantity": "5 kg per person per month"},
        "required_documents": ["Ration Card", "Aadhaar Card", "Residence Proof"],
    },
    {
        "name": "Integrated Child Development Services",
        "name_hindi": "एकीकृत बाल विकास सेवाएँ",
        "category": "women_child",
        "ministry": "Ministry of Women and Child Development",
        "eligibility_criteria": {"target": "Children below 6 years, pregnant women, lactating mothers", "bpl": "Priority to BPL families"},
        "benefits": {"type": "Supplementary Nutrition", "features": "Anganwadi services, immunization, health checkups, preschool education"},
        "required_documents": ["Aadhaar Card", "Birth Certificate", "BPL Certificate"],
    },
    {
        "name": "Sarva Shiksha Abhiyan",
        "name_hindi": "सर्व शिक्षा अभियान",
        "category": "education",
        "ministry": "Ministry of Education",
        "eligibility_criteria": {"target": "All children aged 6-14 years"},
        "benefits": {"type": "Free Education", "features": "Free textbooks, uniforms, mid-day meals, infrastructure improvement"},
        "required_documents": ["Birth Certificate", "Aadhaar Card", "BPL Certificate"],
    },
    {
        "name": "Mid-Day Meal Scheme",
        "name_hindi": "मध्याह्न भोजन योजना",
        "category": "education",
        "ministry": "Ministry of Education",
        "eligibility_criteria": {"target": "All children in government and government-aided schools", "classes": "Class 1 to 8"},
        "benefits": {"type": "Nutritious Meal", "calories": "Minimum 450-700 calories per day", "frequency": "Every school day"},
        "required_documents": ["School Enrollment", "Aadhaar Card"],
    },
    {
        "name": "Rashtriya Madhyamik Shiksha Abhiyan",
        "name_hindi": "राष्ट्रीय माध्यमिक शिक्षा अभियान",
        "category": "education",
        "ministry": "Ministry of Education",
        "eligibility_criteria": {"target": "All children aged 14-18 years"},
        "benefits": {"type": "Secondary Education", "features": "Infrastructure development, teacher training, girls' hostel construction"},
        "required_documents": ["Birth Certificate", "Aadhaar Card"],
    },
    {
        "name": "Pradhan Mantri Vaya Vandana Yojana",
        "name_hindi": "प्रधानमंत्री वाया वंदना योजना",
        "category": "pension",
        "ministry": "Ministry of Finance",
        "eligibility_criteria": {"age": "60 years and above"},
        "benefits": {"type": "Pension", "pension_rate": "7.4% to 7.6% per annum", "tenure": "10 years", "max_pension": "₹5,000 per month"},
        "required_documents": ["Aadhaar Card", "Age Proof", "Bank Account"],
    },
    {
        "name": "National Health Mission",
        "name_hindi": "राष्ट्रीय स्वास्थ्य मिशन",
        "category": "health",
        "ministry": "Ministry of Health and Family Welfare",
        "eligibility_criteria": {"target": "Entire population, especially rural and vulnerable"},
        "benefits": {"type": "Healthcare Services", "features": "ASHA workers, Janani Suraksha Yojana, disease control programs"},
        "required_documents": ["Aadhaar Card"],
    },
    {
        "name": "Skill Acquisition and Knowledge Awareness for Livelihood Promotion",
        "name_hindi": "आजीविका संवर्धन के लिए कौशल अधिग्रहण और ज्ञान जागरूकता",
        "category": "skill_development",
        "ministry": "Ministry of Skill Development and Entrepreneurship",
        "eligibility_criteria": {"target": "School dropouts (Class 8-12)", "age": "15 to 35 years"},
        "benefits": {"type": "Skill Training", "stipend": "₹5,000-₹6,000 depending on course", "duration": "3-12 months"},
        "required_documents": ["Aadhaar Card", "Education Certificate", "Bank Account"],
    },
    {
        "name": "National Rural Livelihoods Mission - Aajeevika",
        "name_hindi": "राष्ट्रीय ग्रामीण आजीविका मिशन - आजीविका",
        "category": "livelihood",
        "ministry": "Ministry of Rural Development",
        "eligibility_criteria": {"target": "Rural poor households", "group": "Self Help Groups (SHGs)"},
        "benefits": {"type": "Livelihood Support", "features": "Bank credit linkage, skill training, market access", "interest_subvention": "Subsidized interest rates on bank loans"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Bank Account"],
    },
    {
        "name": "National Urban Livelihoods Mission",
        "name_hindi": "राष्ट्रीय शहरी आजीविका मिशन",
        "category": "livelihood",
        "ministry": "Ministry of Housing and Urban Affairs",
        "eligibility_criteria": {"target": "Urban poor, especially street vendors, domestic workers"},
        "benefits": {"type": "Urban Livelihood Support", "features": "SHG formation, skill training, shelter for urban homeless"},
        "required_documents": ["Aadhaar Card", "BPL Certificate", "Bank Account"],
    },
    {
        "name": "Pradhan Mantri Street Vendor's AtmaNirbhar Nidhi",
        "name_hindi": "प्रधानमंत्री स्ट्रीट वेंडर आत्मनिर्भर निधि",
        "category": "finance",
        "ministry": "Ministry of Housing and Urban Affairs",
        "eligibility_criteria": {"occupation": "Street vendors", "age": "18 years and above"},
        "benefits": {"type": "Working Capital Loan", "amount": "Up to ₹10,000", "interest": "Subsidized interest rate", "repayment": "Monthly instalments over 1 year"},
        "required_documents": ["Aadhaar Card", "Vending Certificate", "Bank Account"],
    },
    {
        "name": "One Nation One Ration Card",
        "name_hindi": "एक राष्ट्र एक राशन कार्ड",
        "category": "food",
        "ministry": "Ministry of Consumer Affairs, Food and Public Distribution",
        "eligibility_criteria": {"target": "NFSA beneficiaries", "ration_card": "Valid ration card portable across India"},
        "benefits": {"type": "Portable Ration", "coverage": "Can get subsidized food grains anywhere in India"},
        "required_documents": ["Ration Card", "Aadhaar Card"],
    },
    {
        "name": "Indira Gandhi National Old Age Pension Scheme",
        "name_hindi": "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना",
        "category": "pension",
        "ministry": "Ministry of Rural Development",
        "eligibility_criteria": {"age": "60 years and above", "target": "BPL households"},
        "benefits": {"type": "Old Age Pension", "amount_60_79": "₹200 per month", "amount_80_plus": "₹500 per month"},
        "required_documents": ["Aadhaar Card", "Age Proof", "BPL Certificate", "Bank Account"],
    },
    {
        "name": "Indira Gandhi National Widow Pension Scheme",
        "name_hindi": "इंदिरा गांधी राष्ट्रीय विधवा पेंशन योजना",
        "category": "pension",
        "ministry": "Ministry of Rural Development",
        "eligibility_criteria": {"age": "40 to 59 years", "marital_status": "Widow", "target": "BPL households"},
        "benefits": {"type": "Widow Pension", "amount": "₹200 per month"},
        "required_documents": ["Aadhaar Card", "Husband's Death Certificate", "BPL Certificate", "Bank Account"],
    },
    {
        "name": "Indira Gandhi National Disability Pension Scheme",
        "name_hindi": "इंदिरा गांधी राष्ट्रीय विकलांगता पेंशन योजना",
        "category": "pension",
        "ministry": "Ministry of Rural Development",
        "eligibility_criteria": {"age": "18 to 79 years", "disability": "80% or more disability", "target": "BPL households"},
        "benefits": {"type": "Disability Pension", "amount": "₹200 per month"},
        "required_documents": ["Aadhaar Card", "Disability Certificate", "BPL Certificate", "Bank Account"],
    },
    {
        "name": "National Handloom Development Programme",
        "name_hindi": "राष्ट्रीय हथकरघा विकास कार्यक्रम",
        "category": "livelihood",
        "ministry": "Ministry of Textiles",
        "eligibility_criteria": {"occupation": "Handloom weavers and workers"},
        "benefits": {"type": "Subsidy", "features": "Modern looms, design development, marketing support"},
        "required_documents": ["Aadhaar Card", "Weaver Card", "Bank Account"],
    },
    {
        "name": "Pradhan Mantri Kaushal Kendra",
        "name_hindi": "प्रधानमंत्री कौशल केंद्र",
        "category": "skill_development",
        "ministry": "Ministry of Skill Development and Entrepreneurship",
        "eligibility_criteria": {"age": "15 to 45 years", "job_seeker": "Unemployed youth"},
        "benefits": {"type": "Skill Training", "courses": "Market-linked vocational training", "placement": "Placement assistance provided"},
        "required_documents": ["Aadhaar Card", "Education Certificate", "Bank Account"],
    },
    {
        "name": "PM SVANidhi - PM Street Vendor's AtmaNirbhar Nidhi",
        "name_hindi": "पीएम स्वनिधि - प्रधानमंत्री स्ट्रीट वेंडर आत्मनिर्भर निधि",
        "category": "finance",
        "ministry": "Ministry of Housing and Urban Affairs",
        "eligibility_criteria": {"occupation": "Street vendors", "city": "Urban areas"},
        "benefits": {"type": "Working Capital", "amount": "Up to ₹50,000 (enhanced from ₹10,000)", "interest": "At subsidized rates"},
        "required_documents": ["Aadhaar Card", "Vending Certificate/ID", "Bank Account"],
    },
    {
        "name": "Rashtriya Krishi Vikas Yojana",
        "name_hindi": "राष्ट्रीय कृषि विकास योजना",
        "category": "agriculture",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "eligibility_criteria": {"target": "States and Union Territories for agricultural development"},
        "benefits": {"type": "Agricultural Development", "features": "Crop diversification, soil health, farm mechanization"},
        "required_documents": ["Aadhaar Card", "Land Records"],
    },
    {
        "name": "Soil Health Card Scheme",
        "name_hindi": "मृदा स्वास्थ्य कार्ड योजना",
        "category": "agriculture",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "eligibility_criteria": {"target": "All farmers with land holdings"},
        "benefits": {"type": "Soil Testing", "features": "Soil health report with nutrient recommendations", "frequency": "Every 3 years"},
        "required_documents": ["Aadhaar Card", "Land Records"],
    },
    {
        "name": "Pradhan Mantri Matsya Sampada Yojana",
        "name_hindi": "प्रधानमंत्री मत्स्य संपदा योजना",
        "category": "agriculture",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "eligibility_criteria": {"occupation": "Fishermen, fish farmers, fish vendors", "target": "Marine and inland fisheries"},
        "benefits": {"type": "Fisheries Development", "investment": "₹20,050 crore over 5 years", "features": "Infrastructure, modern equipment, credit support"},
        "required_documents": ["Aadhaar Card", "Fisherman ID Card", "Bank Account"],
    },
    {
        "name": "Animal Husbandry Infrastructure Development Fund",
        "name_hindi": "पशुपालन अवसंरचना विकास निधि",
        "category": "agriculture",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "eligibility_criteria": {"target": "Dairy farmers, animal husbandry entrepreneurs"},
        "benefits": {"type": "Infrastructure Loan", "amount": "₹15,000 crore fund", "interest_subvention": "3% interest subvention"},
        "required_documents": ["Aadhaar Card", "Business Plan", "Bank Account"],
    },
    {
        "name": "National Animal Disease Control Programme",
        "name_hindi": "राष्ट्रीय पशु रोग नियंत्रण कार्यक्रम",
        "category": "agriculture",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "eligibility_criteria": {"target": "All cattle and buffalo owners"},
        "benefits": {"type": "Vaccination", "coverage": "100% vaccination for Foot and Mouth Disease and Brucellosis"},
        "required_documents": ["Aadhaar Card", "Animal Ownership Proof"],
    },
    {
        "name": "Dairy Processing and Infrastructure Development Fund",
        "name_hindi": "डेयरी प्रसंस्करण और अवसंरचना विकास निधि",
        "category": "agriculture",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "eligibility_criteria": {"target": "Milk cooperatives and dairy farmers"},
        "benefits": {"type": "Infrastructure Support", "features": "Milk processing, chilling plants, value addition facilities"},
        "required_documents": ["Aadhaar Card", "Milk Cooperative Registration", "Bank Account"],
    },
    {
        "name": "Credit Guarantee Fund Trust for Micro and Small Enterprises",
        "name_hindi": "सूक्ष्म और लघु उद्यमों के लिए ऋण गारंटी निधि ट्रस्ट",
        "category": "finance",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "eligibility_criteria": {"business": "Micro and small enterprises (new and existing)", "loan_amount": "Up to ₹2 crore"},
        "benefits": {"type": "Credit Guarantee", "coverage": "Up to 85% guarantee cover for collateral-free loans", "features": "No collateral required"},
        "required_documents": ["Business Registration", "Aadhaar Card", "Bank Account"],
    },
    {
        "name": "Prime Minister Employment Generation Programme",
        "name_hindi": "प्रधानमंत्री रोजगार सृजन कार्यक्रम",
        "category": "employment",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "eligibility_criteria": {"age": "18 years and above", "education": "Minimum 8th pass", "project_cost": "Up to ₹50 lakh (manufacturing), ₹20 lakh (service)"},
        "benefits": {"type": "Margin Money Subsidy", "subsidy": "15%-35% of project cost", "max_subsidy": "Up to ₹17.5 lakh for manufacturing, ₹7 lakh for service"},
        "required_documents": ["Aadhaar Card", "Education Certificate", "Project Report", "Bank Account"],
    },
    {
        "name": "Kisan Credit Card Scheme",
        "name_hindi": "किसान क्रेडिट कार्ड योजना",
        "category": "agriculture",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "eligibility_criteria": {"occupation": "Farmers, sharecroppers, tenant farmers", "land_ownership": "All categories of farmers"},
        "benefits": {"type": "Credit Card", "features": "Short-term crop loans up to ₹3 lakh at 4% interest", "additional": "Term loans for agriculture and allied activities"},
        "required_documents": ["Aadhaar Card", "Land Records", "Bank Account", "Photo"],
    },
    {
        "name": "Nai Roshni - Leadership Development for Women",
        "name_hindi": "नई रोशनी - महिलाओं के लिए नेतृत्व विकास",
        "category": "social_welfare",
        "ministry": "Ministry of Minority Affairs",
        "eligibility_criteria": {"gender": "Women only", "age": "18-65 years", "target": "Minority community women"},
        "benefits": {"type": "Leadership Training", "duration": "6 days training programme", "features": "Leadership skills, decision making, legal rights, financial literacy"},
        "required_documents": ["Aadhaar Card", "Community Certificate", "Photo"],
    },
    {
        "name": "Mahila E-Haat",
        "name_hindi": "महिला ई-हाट",
        "category": "livelihood",
        "ministry": "Ministry of Women and Child Development",
        "eligibility_criteria": {"gender": "Women only", "target": "Women entrepreneurs, SHGs, NGOs"},
        "benefits": {"type": "Online Marketing", "platform": "Digital platform for women to showcase products", "features": "Free listing, direct buyer-seller connection"},
        "required_documents": ["Aadhaar Card", "Business Registration", "Bank Account"],
    },
    {
        "name": "National Programme for Dairy Development",
        "name_hindi": "राष्ट्रीय डेयरी विकास कार्यक्रम",
        "category": "agriculture",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "eligibility_criteria": {"target": "Dairy farmers, milk cooperatives"},
        "benefits": {"type": "Dairy Development", "features": "Milk procurement, processing, chilling infrastructure"},
        "required_documents": ["Aadhaar Card", "Dairy Registration", "Bank Account"],
    },
    {
        "name": "Mission for Integrated Development of Horticulture",
        "name_hindi": "बागवानी के एकीकृत विकास के लिए मिशन",
        "category": "agriculture",
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "eligibility_criteria": {"occupation": "Horticulture farmers", "land": "Cultivable land suitable for horticulture"},
        "benefits": {"type": "Horticulture Support", "features": "Plant material, mulching, polyhouse, cold storage subsidy", "subsidy": "Up to 50% for small and marginal farmers"},
        "required_documents": ["Aadhaar Card", "Land Records", "Bank Account"],
    },
]


def upgrade() -> None:
    connection = op.get_bind()
    for scheme in SCHEMES:
        name_hindi = scheme.get("name_hindi", "")
        ministry = scheme.get("ministry", "")
        connection.execute(
            text(
                "INSERT INTO schemes (name, name_hindi, category, ministry, "
                "eligibility_criteria, benefits, required_documents, tags, is_active) "
                "VALUES (:name, :name_hindi, :category, :ministry, "
                ":eligibility_criteria::jsonb, :benefits::jsonb, :required_documents::jsonb, "
                ":tags::jsonb, true)"
            ),
            {
                "name": scheme["name"],
                "name_hindi": name_hindi,
                "category": scheme["category"],
                "ministry": ministry,
                "eligibility_criteria": json.dumps(scheme.get("eligibility_criteria", {})),
                "benefits": json.dumps(scheme.get("benefits", {})),
                "required_documents": json.dumps(scheme.get("required_documents", [])),
                "tags": json.dumps([]),
            },
        )


def downgrade() -> None:
    connection = op.get_bind()
    names = [scheme["name"] for scheme in SCHEMES]
    for name in names:
        connection.execute(
            text("DELETE FROM schemes WHERE name = :name"),
            {"name": name},
        )
