apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gramsathi

commonLabels:
  app.kubernetes.io/name: gramsathi
  app.kubernetes.io/part-of: gramsathi-ai

resources:
  - namespace.yaml
  - service-account.yaml
  - ingress.yaml
  - configmap.yaml
  - network-policy.yaml
  - hpa.yaml
  - services.yaml
