apiVersion: v1
kind: ServiceAccount
metadata:
  name: gramsathi-sa
  namespace: gramsathi
  annotations:
    iam.gke.io/gcp-service-account: gramsathi-app@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: gramsathi
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: gramsathi-ai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gramsathi-ai-sa
  namespace: gramsathi
  annotations:
    iam.gke.io/gcp-service-account: gramsathi-ai@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: gramsathi
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: gramsathi-ai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gramsathi-ml-sa
  namespace: gramsathi
  annotations:
    iam.gke.io/gcp-service-account: gramsathi-ml@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: gramsathi
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: gramsathi-ai
