#!/usr/bin/env python3
"""Seed 60 government schemes into PostgreSQL with upsert logic."""

import argparse
import os
import sys
from typing import Optional

import asyncio
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy import text, MetaData, Table, Column, String, Text, Boolean, Float, DateTime, Integer
from sqlalchemy.dialects.postgresql import UUID

SCHEMES = [
    {
        "code": "pm-kisan",
        "name": "PM Kisan Samman Nidhi",
        "ministry": "Ministry of Agriculture",
        "category": "agriculture",
        "summary": "Income support of Rs. 6000/year to landholding farmers",
        "eligibility": "Small and marginal landholding farmers",
        "benefits": "Rs. 6000 per year in three installments",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-fasal-bima",
        "name": "PM Fasal Bima Yojana",
        "ministry": "Ministry of Agriculture",
        "category": "agriculture",
        "summary": "Crop insurance scheme for farmers against crop loss",
        "eligibility": "All farmers growing notified crops",
        "benefits": "Insurance coverage for crop loss, damage, and failure",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "kisan-credit-card",
        "name": "Kisan Credit Card",
        "ministry": "Ministry of Agriculture",
        "category": "agriculture",
        "summary": "Short-term credit to farmers at subsidized rates",
        "eligibility": "Farmers, sharecroppers, tenant farmers",
        "benefits": "Credit up to Rs. 3 lakh at 4% interest",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "soil-health-card",
        "name": "Soil Health Card Scheme",
        "ministry": "Ministry of Agriculture",
        "category": "agriculture",
        "summary": "Soil health assessment and recommendations",
        "eligibility": "All farmers",
        "benefits": "Free soil testing and recommendations",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pmkrish-sinchayee",
        "name": "PM Krishi Sinchayee Yojana",
        "ministry": "Ministry of Agriculture",
        "category": "agriculture",
        "summary": "Improve irrigation efficiency and water conservation",
        "eligibility": "Farmers in water-stressed areas",
        "benefits": "Subsidy on drip/sprinkler irrigation systems",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-ayushman",
        "name": "Ayushman Bharat PM-JAY",
        "ministry": "Ministry of Health",
        "category": "health",
        "summary": "Health insurance coverage for secondary and tertiary care",
        "eligibility": "Families identified in SECC database",
        "benefits": "Health cover of Rs. 5 lakh per family per year",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "janani-suraksha",
        "name": "Janani Suraksha Yojana",
        "ministry": "Ministry of Health",
        "category": "health",
        "summary": "Maternal health and cash assistance for childbirth",
        "eligibility": "Pregnant women in Below Poverty Line families",
        "benefits": "Cash assistance up to Rs. 1400 for institutional delivery",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-matru-vandana",
        "name": "PM Matru Vandana Yojana",
        "ministry": "Ministry of Health",
        "category": "health",
        "summary": "Cash incentive for first live birth",
        "eligibility": "Pregnant and lactating women (first child)",
        "benefits": "Rs. 5000 in three installments",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "rashtriya-swasthya",
        "name": "Rashtriya Swasthya Bima Yojana",
        "ministry": "Ministry of Health",
        "category": "health",
        "summary": "Health insurance for Below Poverty Line families",
        "eligibility": "BPL families",
        "benefits": "Health cover up to Rs. 30,000 per family",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "mission-indradhanush",
        "name": "Mission Indradhanush",
        "ministry": "Ministry of Health",
        "category": "health",
        "summary": "Full immunization of unvaccinated children",
        "eligibility": "Children under 2 years and pregnant women",
        "benefits": "Free vaccination against 12 vaccine-preventable diseases",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "aayushman-bharat-hwc",
        "name": "Ayushman Bharat Health & Wellness Centres",
        "ministry": "Ministry of Health",
        "category": "health",
        "summary": "Comprehensive primary healthcare at HWCs",
        "eligibility": "All citizens",
        "benefits": "Free primary healthcare services",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-kaushal-vikas",
        "name": "PM Kaushal Vikas Yojana",
        "ministry": "Ministry of Skill Development",
        "category": "skill",
        "summary": "Skill training for youth with certification",
        "eligibility": "Youth aged 15-45 years",
        "benefits": "Free skill training and certification",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "deendayal-upadhyay",
        "name": "Deendayal Upadhyay Gram Jyoti Yojana",
        "ministry": "Ministry of Power",
        "category": "infrastructure",
        "summary": "Electrification of rural households",
        "eligibility": "Unelectrified rural households",
        "benefits": "Free electricity connection",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "ujwala",
        "name": "Ujjwala Yojana",
        "ministry": "Ministry of Petroleum",
        "category": "energy",
        "summary": "Free LPG connections to Below Poverty Line households",
        "eligibility": "BPL households with no LPG connection",
        "benefits": "Free LPG connection with first refill",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-awas",
        "name": "PM Awas Yojana - Gramin",
        "ministry": "Ministry of Rural Development",
        "category": "housing",
        "summary": "Housing for all rural households",
        "eligibility": "Households with kutcha house or no house",
        "benefits": "Rs. 1.20 lakh for house construction",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "mg-nrega",
        "name": "Mahatma Gandhi NREGA",
        "ministry": "Ministry of Rural Development",
        "category": "employment",
        "summary": "Guaranteed 100 days of wage employment",
        "eligibility": "Adult members of rural households",
        "benefits": "100 days of guaranteed wage employment per year",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-svanidhi",
        "name": "PM Street Vendor's AtmaNirbhar Nidhi",
        "ministry": "Ministry of Housing & Urban Affairs",
        "category": "finance",
        "summary": "Working capital loans for street vendors",
        "eligibility": "Street vendors with vending license",
        "benefits": "Loan up to Rs. 10,000 with 7% interest subsidy",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-mudra",
        "name": "PM Mudra Yojana",
        "ministry": "Ministry of Finance",
        "category": "finance",
        "summary": "Loans up to Rs. 10 lakh for small businesses",
        "eligibility": "Small business owners, entrepreneurs",
        "benefits": "Collateral-free loans up to Rs. 10 lakh",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "standup-india",
        "name": "Stand Up India",
        "ministry": "Ministry of Finance",
        "category": "finance",
        "summary": "Bank loans for SC/ST and women entrepreneurs",
        "eligibility": "SC/ST or women entrepreneurs",
        "benefits": "Loans from Rs. 10 lakh to Rs. 1 crore",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-suraksha-bima",
        "name": "PM Suraksha Bima Yojana",
        "ministry": "Ministry of Finance",
        "category": "insurance",
        "summary": "Accident insurance cover",
        "eligibility": "All citizens aged 18-70 with bank account",
        "benefits": "Rs. 2 lakh accidental death/disability cover at Rs. 20/year",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-jeevan-jyoti",
        "name": "PM Jeevan Jyoti Bima Yojana",
        "ministry": "Ministry of Finance",
        "category": "insurance",
        "summary": "Life insurance cover",
        "eligibility": "All citizens aged 18-50 with bank account",
        "benefits": "Rs. 2 lakh life cover at Rs. 436/year",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "atal-pension",
        "name": "Atal Pension Yojana",
        "ministry": "Ministry of Finance",
        "category": "pension",
        "summary": "Guaranteed pension for unorganized sector",
        "eligibility": "Citizens aged 18-40 in unorganized sector",
        "benefits": "Guaranteed pension of Rs. 1000-5000/month after 60",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-shram-yogi",
        "name": "PM Shram Yogi Maandhan",
        "ministry": "Ministry of Labour",
        "category": "pension",
        "summary": "Pension for unorganized workers",
        "eligibility": "Unorganized workers aged 18-40 with monthly income below Rs. 15000",
        "benefits": "Guaranteed pension of Rs. 3000/month after 60",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": 15000,
    },
    {
        "code": "rural-pension",
        "name": "Indira Gandhi National Old Age Pension Scheme",
        "ministry": "Ministry of Rural Development",
        "category": "pension",
        "summary": "Pension for elderly Below Poverty Line citizens",
        "eligibility": "Aged 60+ and BPL",
        "benefits": "Rs. 200/month (60-79), Rs. 500/month (80+)",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "rural-disability-pension",
        "name": "Indira Gandhi National Disability Pension Scheme",
        "ministry": "Ministry of Rural Development",
        "category": "pension",
        "summary": "Pension for disabled Below Poverty Line persons",
        "eligibility": "BPL persons with 80%+ disability aged 18-79",
        "benefits": "Rs. 300/month",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "rural-widow-pension",
        "name": "Indira Gandhi National Widow Pension Scheme",
        "ministry": "Ministry of Rural Development",
        "category": "pension",
        "summary": "Pension for widows Below Poverty Line",
        "eligibility": "BPL widows aged 40-79",
        "benefits": "Rs. 300/month",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "sukanya-samriddhi",
        "name": "Sukanya Samriddhi Yojana",
        "ministry": "Ministry of Finance",
        "category": "education",
        "summary": "Savings scheme for girl child education and marriage",
        "eligibility": "Girl child under 10 years",
        "benefits": "High interest savings account with tax benefits",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "national-scholarship",
        "name": "National Scholarship Portal",
        "ministry": "Ministry of Education",
        "category": "education",
        "summary": "Central sector scholarship schemes for students",
        "eligibility": "Students from economically weaker sections",
        "benefits": "Scholarships for school and college education",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": 250000,
    },
    {
        "code": "mid-day-meal",
        "name": "Mid-Day Meal Scheme",
        "ministry": "Ministry of Education",
        "category": "education",
        "summary": "Free cooked meals for school children",
        "eligibility": "Children in government and aided schools",
        "benefits": "Free nutritious cooked meal daily",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "sarva-shiksha",
        "name": "Sarva Shiksha Abhiyan",
        "ministry": "Ministry of Education",
        "category": "education",
        "summary": "Universalization of elementary education",
        "eligibility": "Children aged 6-14 years",
        "benefits": "Free and compulsory education",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "anna-dhan",
        "name": "National Food Security Act - Antyodaya Anna Yojana",
        "ministry": "Ministry of Consumer Affairs",
        "category": "food",
        "summary": "Subsidized food grains for poorest households",
        "eligibility": "Poorest of the poor households",
        "benefits": "35 kg of food grains per month at Rs. 1-3/kg",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pds",
        "name": "Public Distribution System",
        "ministry": "Ministry of Consumer Affairs",
        "category": "food",
        "summary": "Subsidized food grains and essential commodities",
        "eligibility": "Below Poverty Line and Above Poverty Line families",
        "benefits": "Wheat at Rs. 2/kg, Rice at Rs. 3/kg",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-poshan",
        "name": "PM POSHAN (Mid Day Meal)",
        "ministry": "Ministry of Education",
        "category": "nutrition",
        "summary": "Nutrition support for school children",
        "eligibility": "Children in classes 1-8 in government schools",
        "benefits": "Hot cooked meal with nutritional standards",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "jana-dhan",
        "name": "PM Jan Dhan Yojana",
        "ministry": "Ministry of Finance",
        "category": "finance",
        "summary": "Financial inclusion - universal bank accounts",
        "eligibility": "All citizens",
        "benefits": "Zero-balance account, Rs. 1 lakh accident cover, overdraft up to Rs. 10,000",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "digital-india",
        "name": "Digital India Programme",
        "ministry": "Ministry of Electronics & IT",
        "category": "technology",
        "summary": "Digital infrastructure and services for citizens",
        "eligibility": "All citizens",
        "benefits": "Digital services, e-governance, digital literacy",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "bharat-net",
        "name": "BharatNet (National Optical Fibre Network)",
        "ministry": "Ministry of Communications",
        "category": "technology",
        "summary": "Broadband connectivity to all gram panchayats",
        "eligibility": "Gram panchayats",
        "benefits": "High-speed broadband connectivity",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-sahaj-bijli",
        "name": "Saubhagya (PM Sahaj Bijli Har Ghar Yojana)",
        "ministry": "Ministry of Power",
        "category": "energy",
        "summary": "Universal household electrification",
        "eligibility": "Unelectrified households",
        "benefits": "Free electricity connection",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "startup-india",
        "name": "Startup India",
        "ministry": "Ministry of Commerce",
        "category": "employment",
        "summary": "Ecosystem for startups and innovation",
        "eligibility": "Startups registered under DPIIT",
        "benefits": "Tax exemption, funding, mentorship",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "make-in-india",
        "name": "Make in India",
        "ministry": "Ministry of Commerce",
        "category": "employment",
        "summary": "Manufacturing sector promotion",
        "eligibility": "Manufacturing enterprises",
        "benefits": "Policy support, ease of doing business",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-egscholarship",
        "name": "PM Employment Generation Programme",
        "ministry": "Ministry of MSME",
        "category": "employment",
        "summary": "Self-employment opportunities for unemployed",
        "eligibility": "Unemployed youth aged 18+",
        "benefits": "Subsidy for setting up micro-enterprises",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "nulk-registration",
        "name": "National Unorganised Labour Registration",
        "ministry": "Ministry of Labour",
        "category": "employment",
        "summary": "Registration of unorganized workers",
        "eligibility": "Unorganized workers aged 16-59",
        "benefits": "Access to social security schemes",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-vishwakarma",
        "name": "PM Vishwakarma Yojana",
        "ministry": "Ministry of Micro, Small & Medium Enterprises",
        "category": "skill",
        "summary": "Credit support for traditional artisans and craftspeople",
        "eligibility": "Traditional artisans and craftspeople",
        "benefits": "Loan up to Rs. 1 lakh (first tranche), Rs. 2 lakh (second tranche)",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "rashtriya-gramin",
        "name": "Rashtriya Gramin Swasthya Mission",
        "ministry": "Ministry of Health",
        "category": "health",
        "summary": "Healthcare access in rural areas",
        "eligibility": "Rural population",
        "benefits": "Mobile health units, telemedicine services",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "swachh-bharat",
        "name": "Swachh Bharat Mission - Gramin",
        "ministry": "Ministry of Drinking Water & Sanitation",
        "category": "sanitation",
        "summary": "Sanitation and cleanliness in rural areas",
        "eligibility": "Rural households without toilets",
        "benefits": "Financial assistance for toilet construction",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "jal-jeevan",
        "name": "Jal Jeevan Mission",
        "ministry": "Ministry of Drinking Water & Sanitation",
        "category": "infrastructure",
        "summary": "Tap water connection to every rural household",
        "eligibility": "Rural households without tap water",
        "benefits": "Functional tap water connection",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-gram-sadak",
        "name": "PM Gram Sadak Yojana",
        "ministry": "Ministry of Rural Development",
        "category": "infrastructure",
        "summary": "All-weather road connectivity to rural habitations",
        "eligibility": "Unconnected rural habitations",
        "benefits": "All-weather road connectivity",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "digital-arogya",
        "name": "Ayushman Bharat Digital Mission",
        "ministry": "Ministry of Health",
        "category": "health",
        "summary": "Digital health IDs for all citizens",
        "eligibility": "All citizens",
        "benefits": "Digital health ID, electronic health records",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "one-nation-card",
        "name": "One Nation One Ration Card",
        "ministry": "Ministry of Consumer Affairs",
        "category": "food",
        "summary": "Portable ration card for interstate migrants",
        "eligibility": "All ration card holders",
        "benefits": "Access PDS anywhere in India",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "e-shram",
        "name": "e-Shram Portal",
        "ministry": "Ministry of Labour",
        "category": "employment",
        "summary": "National database of unorganized workers",
        "eligibility": "Unorganized workers aged 16-59",
        "benefits": "Accidental insurance cover of Rs. 2 lakh",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "mera-gaon-digital",
        "name": "Mera Gaon Meri Digital Duniya",
        "ministry": "Ministry of Rural Development",
        "category": "technology",
        "summary": "Digital literacy for rural citizens",
        "eligibility": "Rural citizens aged 15+",
        "benefits": "Free digital literacy training",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-scholarship-tier",
        "name": "PM Scholarship for Central Armed Forces",
        "ministry": "Ministry of Defence",
        "category": "education",
        "summary": "Scholarships for wards of CAPF personnel",
        "eligibility": "Children of CAPF/ARMY personnel",
        "benefits": "Rs. 2000-2500/month scholarship",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "nari-shakti",
        "name": "Nari Shakti Puraskar",
        "ministry": "Ministry of Women & Child Development",
        "category": "women",
        "summary": "Recognition of women's achievements",
        "eligibility": "Women excelling in various fields",
        "benefits": "Recognition and cash award",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-care-child",
        "name": "PM CARES for Children",
        "ministry": "Prime Minister's Office",
        "category": "education",
        "summary": "Support for children orphaned during COVID-19",
        "eligibility": "Children who lost both parents during COVID-19",
        "benefits": "Education scholarship, healthcare, insurance cover",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "national-ayush",
        "name": "National Ayush Mission",
        "ministry": "Ministry of Ayush",
        "category": "health",
        "summary": "Promotion of traditional Indian medicine",
        "eligibility": "All citizens",
        "benefits": "Ayush healthcare services",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-msme",
        "name": "PM MSME Scheme",
        "ministry": "Ministry of MSME",
        "category": "employment",
        "summary": "Support for micro, small and medium enterprises",
        "eligibility": "MSME registered businesses",
        "benefits": "Collateral-free loans, credit guarantees",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "khelo-india",
        "name": "Khelo India",
        "ministry": "Ministry of Sports",
        "category": "sports",
        "summary": "Grassroots sports development",
        "eligibility": "Young athletes aged 8-18",
        "benefits": "Athlete training, equipment, competition exposure",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "national-placement",
        "name": "National Career Service",
        "ministry": "Ministry of Labour",
        "category": "employment",
        "summary": "Job placement and career counseling",
        "eligibility": "Job seekers and employers",
        "benefits": "Job matching, skill development, career guidance",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-solar-rooftop",
        "name": "PM Surya Ghar Muft Bijli Yojana",
        "ministry": "Ministry of Power",
        "category": "energy",
        "summary": "Rooftop solar for households",
        "eligibility": "Households with suitable rooftop",
        "benefits": "Subsidy up to Rs. 78,000 for rooftop solar installation",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "rashtriya-poshan",
        "name": "POSHAN Abhiyaan",
        "ministry": "Ministry of Women & Child Development",
        "category": "nutrition",
        "summary": "National nutrition mission for children and women",
        "eligibility": "Children under 6, adolescent girls, pregnant women",
        "benefits": "Nutritional support, counseling, monitoring",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-budget-scholarship",
        "name": "Central Sector Scholarship Scheme",
        "ministry": "Ministry of Education",
        "category": "education",
        "summary": "Scholarships for meritorious students from poor families",
        "eligibility": "Students with family income below Rs. 8 lakh/year",
        "benefits": "Rs. 10,000-20,000 per year",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": 800000,
    },
    {
        "code": "national-handicraft",
        "name": "National Handicraft Development Programme",
        "ministry": "Ministry of Textiles",
        "category": "skill",
        "summary": "Support for artisans and handicraft workers",
        "eligibility": "Traditional artisans and handicraft workers",
        "benefits": "Training, design support, marketing assistance",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
    {
        "code": "pm-youth-skill",
        "name": "PM Yuva Yojana",
        "ministry": "Ministry of Skill Development",
        "category": "skill",
        "summary": "Entrepreneurship and skill development for youth",
        "eligibility": "Youth aged 15-29",
        "benefits": "Entrepreneurship training, mentoring, funding",
        "application_mode": "online",
        "state_specific": False,
        "income_limit": None,
    },
]


async def upsert_schemes(connection_string: str):
    engine = create_async_engine(connection_string, echo=False)
    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with engine.begin() as conn:
        await conn.execute(text("""
            CREATE TABLE IF NOT EXISTS schemes (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                code VARCHAR(50) UNIQUE NOT NULL,
                name VARCHAR(255) NOT NULL,
                ministry VARCHAR(255) NOT NULL,
                category VARCHAR(100) NOT NULL,
                summary TEXT,
                eligibility TEXT,
                benefits TEXT,
                application_mode VARCHAR(50) DEFAULT 'online',
                state_specific BOOLEAN DEFAULT FALSE,
                income_limit NUMERIC(12, 2),
                is_active BOOLEAN DEFAULT TRUE,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            )
        """))

    count = 0
    async with session_factory() as session:
        for scheme in SCHEMES:
            result = await session.execute(
                text("SELECT id, name, summary, eligibility, benefits FROM schemes WHERE code = :code"),
                {"code": scheme["code"]},
            )
            existing = result.fetchone()

            if existing:
                changed = (
                    existing[1] != scheme["name"]
                    or existing[2] != scheme.get("summary")
                    or existing[3] != scheme.get("eligibility")
                    or existing[4] != scheme.get("benefits")
                )
                if changed:
                    await session.execute(
                        text("""
                            UPDATE schemes SET
                                name = :name,
                                ministry = :ministry,
                                category = :category,
                                summary = :summary,
                                eligibility = :eligibility,
                                benefits = :benefits,
                                application_mode = :application_mode,
                                state_specific = :state_specific,
                                income_limit = :income_limit,
                                updated_at = NOW()
                            WHERE code = :code
                        """),
                        scheme,
                    )
                    count += 1
            else:
                await session.execute(
                    text("""
                        INSERT INTO schemes (code, name, ministry, category, summary, eligibility, benefits,
                                             application_mode, state_specific, income_limit)
                        VALUES (:code, :name, :ministry, :category, :summary, :eligibility, :benefits,
                                :application_mode, :state_specific, :income_limit)
                    """),
                    scheme,
                )
                count += 1

        await session.commit()

    await engine.dispose()
    return count


def main():
    parser = argparse.ArgumentParser(description="Seed government schemes into PostgreSQL")
    parser.add_argument("--connection", help="PostgreSQL connection string (async)", default=None)
    args = parser.parse_args()

    conn = args.connection or os.getenv("DATABASE_URL")
    if not conn:
        print("ERROR: Provide --connection argument or set DATABASE_URL environment variable")
        sys.exit(1)

    count = asyncio.run(upsert_schemes(conn))
    print(f"Seeded/updated {count} schemes successfully")


if __name__ == "__main__":
    main()
